[colors]
black = "#101116"
white = "#f1f5f9"
orange = "#fb9b64"
orange-dark = "#bb774f"
gray = "#44475a"
cyan = "#27a1b9"
cyan-dark = "#1e5060"

[base.focused]
foreground = "white"
background = "black"

[base.unfocused]
foreground = "gray"
background = "black"

[highlight.focused]
foreground = "orange"
background = "black"

[highlight.unfocused]
foreground = "orange-dark"
background = "black"

[title.focused]
foreground = "cyan"
background = "black"

[title.unfocused]
foreground = "cyan-dark"
background = "black"

[border.focused]
foreground = "white"
background = "black"

[border.unfocused]
foreground = "gray"
background = "black"

[footer]
hide = false

[status]
hide = false
