[colors]
black = "#101116"
white = "#f1f5f9"
magenta = "#ff33cc"
orange = "#fb9b64"
orange-subdued = "#bb774f"
green = "#00cc66"
gray = "#44475a"
cyan = "#27a1b9"
cyan-subdued = "#226f82"

[base]
background = "black"
foreground = "white"

[disabled]
background = "black"
foreground = "gray"

[border.focused]
foreground = "white"

[border.unfocused]
foreground = "gray"

[border.text.unfocused]
foreground = "gray"

[border.text.focused]
foreground = "cyan"

[navbar.title]
foreground = "orange"
bold = true

[navbar.tabs.focused]
foreground = "cyan"
background = "black"

[navbar.tabs.unfocused]
foreground = "gray"
background = "black"

[list.active.selected]
foreground = "black"
background = "orange"

[list.active.unselected]
foreground = "white"
background = "black"

[list.inactive.selected]
foreground = "black"
background = "orange-subdued"

[list.inactive.unselected]
foreground = "gray"
background = "black"

[history.inactive.unfocused]
foreground = "gray"
background = "black"

[history.inactive.focused]
foreground = "black"
background = "gray"

[history.active.unfocused]
foreground = "orange-subdued"
background = "black"

[history.active.focused]
foreground = "black"
background = "orange-subdued"

[headers.titles.unfocused]
foreground = "gray"
background = "black"

[headers.titles.focused]
foreground = "cyan"
background = "black"

[headers.tabs.active.focused]
foreground = "cyan"
background = "black"

[headers.tabs.inactive.focused]
foreground = "cyan-subdued"
background = "black"

[headers.tabs.inactive.unfocused]
foreground = "gray"
background = "black"

[editor.text]
foreground = "white"
background = "black"

[editor.cursor]
foreground = "black"
background = "white"

[editor.selection]
foreground = "black"
background = "orange"

[editor.status_line]
bold = false

[editor.status_line.primary]
foreground = "black"
background = "orange-subdued"

[editor.status_line.secondary]
background = "black"

[footer]
hide = false

[footer.text]
foreground = "gray"
background = "black"

[footer.tabs]
foreground = "cyan-subdued"
background = "black"

[help_dialog]
background = "black"
foreground = "white"
