[colors]
black = "#101116"
white = "#f1f5f9"
magenta = "#ff33cc"
orange = "#ff9900"
green = "#00cc66"
gray = "#44475a"

[base]
foreground = "white"

[border.text.focused]
foreground = "magenta"

[navbar.title]
foreground = "magenta"
bold = true

[navbar.tabs.focused]
foreground = "black"
background = "green"

[list.focused]
foreground = "black"
background = "orange"

[history.inactive.unfocused]
foreground = "gray"

[history.inactive.focused]
foreground = "black"
background = "gray"

[history.active.unfocused]
foreground = "orange"

[history.active.focused]
foreground = "black"
background = "orange"

[headers.titles]
foreground = "magenta"
bold = true

[headers.tabs.focused]
foreground = "black"
background = "orange"

[editor.cursor]
foreground = "black"
background = "white"

[editor.selection]
foreground = "black"
background = "orange"

[editor.status_line]
bold = false

[editor.status_line.primary]
foreground = "black"
background = "green"

[footer]
hide = false

[footer.text]
foreground = "gray"

[footer.tabs]
foreground = "black"
background = "gray"
