includes = [
    "$HOME/Rust/wireman/example",
]
files = [
    "grpc_simple/debugger.proto",
    "grpc_simple/greeter.proto",
    "grpc_simple/productfinder.proto",
    "grpc_simple/timekeeper.proto",
]

[server]
default_address = "http://localhost:50051"

[history]
autosave = true
