includes = [
    "$HOME/Rust/wireman/example",
]
files = [
    "grpc_simple/debugger.proto",
    "grpc_simple/greeter.proto",
    "grpc_simple/productfinder.proto",
    "grpc_simple/timekeeper.proto",
]

[server]
default_address = "http://localhost:50051"

# [history]
# autosave = true
# directory = "$WIREMAN_CONFIG_DIR/history"

# [logging]
# directory = "$WIREMAN_CONFIG_DIR"

# [ui]
# hide_footer_help = false
