[workspace]

members = [
    "wireman-core",
    "wireman-config",
    "wireman-logger",
    "wireman-theme",
    "wireman",
    "wireman-event-handler",
]

default-members = ["wireman"]

resolver = "2"
