[base]
background = "#282a36"
foreground = "#f8f8f2"

[border.text.unfocused]
foreground = "#ff79C6"

[border.text.focused]
foreground = "#ff79C6"

[navbar.title]
foreground = "#ff79C6"
bold = true

[navbar.tabs.unfocused]
foreground = "#f8f8f2"
background = "#282a36"

[navbar.tabs.focused]
foreground = "#282a36"
background = "#ffb86c"

[list.focused]
foreground = "#282a36"
background = "#8be9df"

[history.inactive.unfocused]
foreground = "#44475a"
background = "#282a36"

[history.inactive.focused]
foreground = "#282a36"
background = "#44475a"

[history.active.unfocused]
foreground = "#8be9df"
background = "#282a36"

[history.active.focused]
foreground = "#282a36"
background = "#8be9df"

[editor.selection]
foreground = "#282a36"
background = "#f1fa8c"

[editor.status_line]
bold = true

[editor.status_line.primary]
foreground = "#282a36"
background = "#ff79C6"

[editor.status_line.secondary]
background = "#44475A"

[headers.titles]
foreground = "#ff79C6"
background = "#282a36"
bold = true

[headers.tabs.focused]
foreground = "#282a36"
background = "#8be9df"

[footer]
hide = true
# [footer.tabs]
# background = "#6272A4"
# [footer.text]
# foreground = "#44475A"
