# https://draculatheme.com/contribute
# black: #282a36
# white: f8f8f2
# gray: #44475a
# orange: #ffb86c
# purple: #bd93f9
# yellow: #f1fa8c
# green: #50fa7b
# red: #ff5555
# cyan: 8be9fd
# pink: #ff79c6

[base]
background = "#282a36"
foreground = "#f8f8f2"

[border.text.unfocused]
foreground = "#8be9df"

[border.text.focused]
foreground = "#8be9df"

[navbar.title]
foreground = "#bd93f9"
bold = true

[navbar.tabs.unfocused]
foreground = "#ff79c6"
background = "#282a36"

[navbar.tabs.focused]
foreground = "#282a36"
background = "#ff79c6"

[list.focused]
foreground = "#282a36"
background = "#ffb86c"

[history.inactive.unfocused]
foreground = "#44475a"
background = "#282a36"

[history.inactive.focused]
foreground = "#282a36"
background = "#44475a"

[history.active.unfocused]
foreground = "#ffb86c"
background = "#282a36"

[history.active.focused]
foreground = "#282a36"
background = "#ffb86c"

[editor.selection]
foreground = "#282a36"
background = "#f1fa8c"

[editor.status_line]
bold = true

[editor.status_line.primary]
foreground = "#282a36"
background = "#ff79C6"

[editor.status_line.secondary]
background = "#44475A"

[headers.titles]
foreground = "#8be9df"
background = "#282a36"
bold = true

[headers.tabs.focused]
foreground = "#282a36"
background = "#ffb86c"

[footer]
hide = true
# [footer.tabs]
# background = "#6272A4"
# [footer.text]
# foreground = "#44475A"
