[base]
background = "#282a36"
#
[border]
text = "#ff79C6"
text_focused = "#ff79C6"
border = "#f8f8f2"
border_focused = "#f8f8f2"

[navbar]
title = "#ff79C6"
tabs_foreground = "#f8f8f2"
tabs_focused_foreground = "#282a36"
tabs_focused_background = "#8be9df"

[editor]
hide_status_line = true
selection_foreground = "#282a36"
selection_background = "#F1FA8C"

[list]
focused_foreground = "#282a36"
focused_background = "#8be9df"

[headers]
titles_foreground = "#ff79C6"
titles_background = "#282a36"
titles_bold = true 
tabs_focused_foreground = "#282a36"
tabs_focused_background = "#8be9df"

[history]
enabled = "#FFB86C"
disabled = "#44475A"

[help]
hide = true
# key_foreground = "#44475A"
# key_background = "#f8f8f2"
# description_foreground = "#f8f8f2"
