# black #101116
# white #f1f5f9
# gray: #44475a
# neon-magenta: #ff33cc
# neon-green: #00cc66
# neon-orange: #ff9900

[base]
background = "#101116"
foreground = "#f1f5f9"

[border.text.unfocused]
foreground = "#f1f5f9"

[border.text.focused]
foreground = "#f1f5f9"

[navbar.title]
foreground = "#ff33cc"
bold = true

[navbar.tabs.unfocused]
foreground = "#f1f5f9"
background = "#101116"

[navbar.tabs.focused]
foreground = "#101116"
background = "#00cc66"

[list.focused]
foreground = "#101116"
background = "#ff9900"

[history.inactive.unfocused]
foreground = "#44475a"
background = "#101116"

[history.inactive.focused]
foreground = "#101116"
background = "#44475a"

[history.active.unfocused]
foreground = "#ff9900"
background = "#101116"

[history.active.focused]
foreground = "#101116"
background = "#ff9900"

[headers.titles]
foreground = "#f1f5f9"
background = "#101116"
bold = true

[headers.tabs.focused]
foreground = "#101116"
background = "#ff9900"

[editor.selection]
foreground = "#101116"
background = "#ff9900"

[editor.status_line]
bold = false

[editor.status_line.primary]
foreground = "#101116"
background = "#00cc66"

[editor.status_line.secondary]
background = "#101116"

[footer]
hide = false
