[package]
name = "wireman"
version = "0.1.0"
edition = "2021"
authors = ["preiter <phil.reiter93@gmail.com>"]
description = "A TUI based gRPC client"
repository = "https://github.com/preiter93/wireman"
keywords = ["gRPC", "proto", "TUI"]
readme = "README.md"
license = "MIT"
rust-version = "1.70.0"

[dependencies]
core = { package = "wireman-core", path = "../wireman-core", version = "0.1.0" }
config = { package = "wireman-config", path = "../wireman-config", version = "0.1.0" }
logger = { package = "wireman-logger", path = "../wireman-logger", version = "0.1.0" }
theme = { package = "wireman-theme", path = "../wireman-theme", version = "0.1.0" }
tui-widget-list = { version = "0.9.0" }
# tui-widget-list = { git = "https://github.com/preiter93/tui-widget-list.git", branch = "v0.9" }
# tui-widget-list = { path = "../../tui-widget-list", version = "0.9.0"}
tui-key-event-handler = { package = "tui-key-event-handler", path = "../tui-key-event-handler", version = "0.1.0" }
edtui = "0.3.4"
# edtui = { version = "0.3.3", path = "../../edtui" }
crossterm = { version = "0.27", features = ["events", "event-stream"] }
ratatui = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
unicode-width = "0.1"
http = "0.2"
arboard = "3.3.0"
once_cell = "1.19.0"
tokio = { version = "1", features = ["rt", "macros"] }
futures = "0.3"
