[package]
name = "wireman"
version = "0.1.0"
edition = "2021"
authors = ["preiter <phil.reiter93@gmail.com>"]
description = "A TUI based gRPC client"
repository = "https://github.com/preiter93/wireman"
keywords = ["gRPC", "proto", "TUI"]
readme = "README.md"
license = "MIT"

[dependencies]
core = { package = "wireman_core", path = "../wireman-core", version = "0.1.0" }
config = { package = "wireman_config", path = "../wireman-config", version = "0.1.0" }
tui-widget-list = { package = "tui-widget-list", path = "../../tui-widget-list", version = "0.7.2" }
edtui = { package = "edtui", path = "../../edtui", version = "0.3", default-features = false }
crossterm = { version = "0.27", features = ["events", "event-stream"] }
ratatui = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
unicode-width = "0.1"
http = "0.2"
arboard = "3.3.0"
once_cell = "1.19.0"
tokio = "1.35.1"
futures = "0.3"
