[package]
name = "wireman-core"
version = "0.1.0"
edition = "2021"
authors = ["preiter <phil.reiter93@gmail.com>"]
description = "Core for wireman"
repository = "https://github.com/preiter93/wireman"
keywords = ["wireman", "core"]
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
prost = "0.12"
prost-build = "0.12"
prost-types = "0.12"
protox = "0.6"
http = "0.2"
webpki-roots = "0.26"

[dependencies.prost-reflect]
version = "0.13"
features = ["serde", "text-format"]

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread", "sync", "fs"]

[dependencies.tonic]
version = "0.11"

[dependencies.rustls]
version = "0.22.0"

[dependencies.rustls-pemfile]
version = "2.0"

[dependencies.hyper]
version = "0.14"
features = ["client", "http2"]

[dependencies.hyper-rustls]
version = "0.25.0"
features = ["default", "http2"]
