[package]
name = "wireman-core"
version = "0.1.1"
edition = "2021"
authors = ["preiter <phil.reiter93@gmail.com>"]
description = "Core for wireman"
repository = "https://github.com/preiter93/wireman"
keywords = ["wireman", "core"]
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
prost = "0.12"
prost-build = "0.12"
prost-types = "0.12"
protox = "0.6"
http = "1"

[dependencies.prost-reflect]
version = "0.13"
features = ["serde", "text-format"]

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread", "sync", "fs"]

[dependencies.tonic]
version = "0.12"
features = ["tls", "tls-webpki-roots"]

[[example]]
name = "metadata"
