[package]
name = "wireman_config"
version = "0.1.0"
edition = "2021"
authors = ["preiter <phil.reiter93@gmail.com>"]
description = "Config for wireman"
repository = "https://github.com/preiter93/wireman"
keywords = ["gRPC", "proto", "TUI"]
readme = "README.md"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
shellexpand = "3.1.0"
thiserror = "1.0"
toml = "0.8.10"
